[workspace]

members = [
  # tests
  "code/lifetime",
  "code/strtok",
  "code/gp",
  "code/primitives",
  "code/network",
  "code/tokio-server",
  "code/simple_asm",

  # live coding
  "live_coding/hello_world",
]
